### ISSUE TITLE
Análise de requisitos

### ISSUE THREAD

**Issue by MtSPereir4** [MtSPereir4/condominus#1]
Reformular os requisitos do projeto Condominus;

**Comment by Pedrotaless** [comment]
Criar cronograma da atividades realizadas até o momento

**Comment by Pedrotaless** [comment]
Dividir módulos de desenvolvimento.

**Comment by MtSPereir4** [comment]
Segue o arquivo referente a revisão de requisitos:
[Revisao_de_Requisitos_Condominus_09_24.docx](https://github.com/user-attachments/files/16878205/Revisao_de_Requisitos_Condominus_09_24.docx)
